version: '3'
volumes:
  data:
  export:
  redis-data:
services:
  postgres:
    image: docker.io/postgres:14-alpine
    container_name: postgres-recipes
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
    volumes:
      - data:/var/lib/postgresql/data
      - export:/export
  redis:
    image: docker.io/redis:6.2
    container_name: redis-recipes
    ports:
      - 5500:6379
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=password
    command: ['redis-server', '--requirepass', 'password']
